name: flutter_wanandroid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.4+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.3
  # Cookie https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_cookie_manager: 1.0.0
  # 轻量级数据存储 https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: ^0.4.3
  # https://github.com/duytq94/flutter-intro-slider
  # intro_slider: ^2.2.6
  # 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # Toast插件 https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.1.0
  # WebView插件 https://pub.flutter-io.cn/packages/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.8
  # webview_flutter
  #webview_flutter: ^0.3.9+1
  # 数据 https://pub.flutter-io.cn/packages/sqflite
  sqflite: ^1.1.3
  # 文件读写 https://pub.dev/packages/path_provider
  path_provider: ^0.5.0+1
  # https://github.com/marcojakob/dart-event-bus
  event_bus: ^1.1.0
  # https://github.com/tekartik/synchronized.dart
  #synchronized: '>=0.1.0 <3.0.0'
  # https://github.com/ReactiveX/rxdart
  #rxdart: ^0.22.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.1+1
  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.1.0
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.3
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  #flustars: 0.2.6+1
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.3
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8
  # share 分享
  share: ^0.6.1+1
  # 上拉加载和下拉刷新的组件 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.5.4
  # 解析html标签 https://github.com/Sub6Resources/flutter_html
  flutter_html: ^0.10.4
  # Html Encoder/Decoder https://pub.dev/packages/html_unescape
  html_unescape: ^1.0.1+3
  # 文字、屏幕适配
  flutter_screenutil: ^0.6.0

  device_info: ^0.4.0+1
  package_info: ^0.4.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    # 加载页面图片资源
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/